### ISSUE TITLE
packaging: make release v2.0

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#240]
Make a new release.

- [x] update changelog (#250)
- [x] make sure that manual pages are up to date with the newly introduced options (#250)
- [x] make sure that the manual page are up to date with respect to the new kind of media that are now handled (#250)
- [x] improve the quickstart guide by adding the directory tree of a gallery, which is a common source of confusion (#250)
- [x] update libs licenses in readme (#250)
- [x] generate packages
- [x] update website
- [x] fix nix package in nixpkgs (#130)

**Comment by pacien** [comment]
Done.
